name: CI
on: [push, pull_request]
jobs:
  test:
    name: Run Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Init workspace
      shell: pwsh
      run: |
        Set-PSRepository PSGallery -InstallationPolicy Trusted
        ./build.ps1 -Task Init -Bootstrap
    - name: CleanUp the workpace
      shell: pwsh
      run: ./build.ps1 -Task Clean
    - name: Build the module
      shell: pwsh
      run: ./build.ps1 -Task Build
    - name: Lint with PSScriptAnalyzer
      shell: pwsh
      run: ./build.ps1 -Task Analzye
    - name: Pester testing
      shell: pwsh
      run: ./build.ps1 -Task Pester
    - name: Publishto PSGallery
      shell: pwsh
      run: ./build.ps1 -Task Publish
