name: CI
on: [push, pull_request]
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Init workspace
      shell: pwsh
      run: ./build.ps1 -Task Test -Bootstrap
      
    - name: pester tests report
      uses: zyborg/pester-tests-report@v1.3.3
      with:
        test_results_path: testResults.xml
        coverage_paths: tests/
        report_name: Pester
        report_title: Pester test
        github_token: ${{ secrets.GH_TOKEN }}
        coverage_results_path: codeCoverage.xml
