name: CI
on: [push, pull_request]
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Init workspace
      shell: pwsh
      run: ./build.ps1 -Task Test -Bootstrap
      
    - name: pester tests report
      uses: zyborg/pester-tests-report@v1.5.0
      with:
        report_name: Pester
        report_title: Pester test
        github_token: ${{ secrets.GITHUB_TOKEN }}
        include_paths: /tests/
        coverage_report_name: CoverageResults
        coverage_paths: /Test/Public/,/Test/Private
